import { ROLES } from "../config/constants.ts";
import Offer from "../entities/Offer.ts";


const testOffers: Offer[] = [
  {
    offerId: 1,
    price: 500,
    comment: "We can deliver within 3 days.",
    deliveryDate: new Date("2024-12-01").toISOString(),
    status: "Pending",
    orderId: 101,
    order: {
      orderId: 101,
      description: "Books and stationery",
      from: "Warehouse A",
      fromLatitude: "30.0444",
      fromLongitude: "31.2357",
      pickupCity: "Cairo",
      to: "Store B",
      toLatitude: "29.9187",
      toLongitude: "31.2001",
      deliveryCity: "Giza",
      createdAt: new Date("2024-11-25"),
      status: "Pending",
      offers: [],
      clientId: "client1",
      client: {
        id: "client1",
        fullName: "John Doe",
        phoneNumber: "+201001234567",
        email: "john.doe@example.com",
        password: "clientpassword",
        role: ROLES.client,
      },
      deliveryPersonNumber: null,
      isFragile: false,
      length: 50,
      width: 40,
      height: 30,
      weight: 20,
      quantity: 10,
    },
    shippingCompanyId: "company1",
    shippingCompany: {
      id: "company1",
      fullName: "Fast Shipping Co.",
      phoneNumber: "+1234567890",
      email: "contact@fastshipping.com",
      password: "securepassword",
      role: ROLES.company,
    },
  },
  {
    offerId: 2,
    price: 450,
    comment: "Cheaper delivery, but it will take 5 days.",
    deliveryDate: new Date("2024-12-03").toISOString(),
    status: "Rejected",
    orderId: 102,
    order: {
      orderId: 102,
      description: "Fragile glassware",
      from: "Factory X",
      fromLatitude: "31.0451",
      fromLongitude: "29.9753",
      pickupCity: "Alexandria",
      to: "Shop Y",
      toLatitude: "30.0626",
      toLongitude: "31.2497",
      deliveryCity: "Cairo",
      createdAt: new Date("2024-11-26"),
      status: "Accepted",
      offers: [],
      clientId: "client2",
      client: {
        id: "client2",
        fullName: "Jane Smith",
        phoneNumber: "+201002345678",
        email: "jane.smith@example.com",
        password: "password123",
        role: ROLES.client,
      },
      deliveryPersonNumber: null,
      isFragile: true,
      length: 30,
      width: 30,
      height: 30,
      weight: 15,
      quantity: 5,
    },
    shippingCompanyId: "company2",
    shippingCompany: {
      id: "company2",
      fullName: "Reliable Movers",
      phoneNumber: "+9876543210",
      email: "support@reliablemovers.com",
      password: "strongpassword",
      role: ROLES.company,
    },
  },
  {
    offerId: 3,
    price: 600,
    comment: "Premium service with 2-day delivery.",
    deliveryDate: new Date("2024-11-30").toISOString(),
    status: "Accepted",
    orderId: 103,
    order: {
      orderId: 103,
      description: "Electronics",
      from: "Tech Warehouse",
      fromLatitude: "30.0131",
      fromLongitude: "31.2089",
      pickupCity: "Cairo",
      to: "Retail Store",
      toLatitude: "30.0626",
      toLongitude: "31.2497",
      deliveryCity: "Alexandria",
      createdAt: new Date("2024-11-24"),
      status: "Pending",
      offers: [],
      clientId: "client3",
      client: {
        id: "client3",
        fullName: "Ali Hassan",
        phoneNumber: "+201003456789",
        email: "ali.hassan@example.com",
        password: "clientsecure",
        role: ROLES.client,
      },
      deliveryPersonNumber: "+201223344556",
      isFragile: false,
      length: 100,
      width: 60,
      height: 40,
      weight: 25,
      quantity: 20,
    },
    shippingCompanyId: "company3",
    shippingCompany: {
      id: "company3",
      fullName: "Express Deliveries",
      phoneNumber: "+1122334455",
      email: "info@expressdeliveries.com",
      password: "password123",
      role: ROLES.company,
    },
  },
];

export default testOffers;
